# -*- coding: utf-8 -*-
"""
Created on Sun Feb  1 15:59:09 2015

Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.

@author: joshjoshly
"""

upper = 4000000
sum = 2 # initial value
fibnm2 = 1
fibnm1 = 2
fibn = 3

while (fibn < upper):
    fibnm2 = fibnm1
    fibnm1 = fibn
    fibn = fibnm1 + fibnm2
    if fibn % 2 == 0:
        sum += fibn
    

print(sum)
